#!/usr/bin/env python3
"""Slice the Soma Cruz sprite sheet (Castlevania: Dawn of Sorrow, asset 19116).

Detects animation rows and individual frames by measuring non-background pixels,
removes the opaque gray-green background to alpha, and emits:
  - imagens/Cruz/cruz-sprite-sheet-clean.png  (transparent render source)
  - modules/cruz_frames.lua                   (explicit per-frame rect manifest)

The sheet is non-uniform: frame widths and heights vary within a row, and some
rows contain two animations separated by a wide gap. anim8 requires uniform grids
and cannot handle this, hence explicit rects.
"""

import json
import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install --break-system-packages Pillow")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "imagens", "Cruz", "cruz-sprite-sheet.png")
CLEAN = os.path.join(ROOT, "imagens", "Cruz", "cruz-sprite-sheet-clean.png")
MANIFEST = os.path.join(ROOT, "modules", "cruz_frames.lua")

BG = (64, 80, 64)
TOL = 18
GAP_RATIO = 2.5
GAP_MIN_EXTRA = 12
MERGE_RATIO = 1.6
NON_ANIMATION_ROWS = {42, 43}


def is_fg(p):
    return abs(p[0] - BG[0]) + abs(p[1] - BG[1]) + abs(p[2] - BG[2]) > TOL


def find_row_bands(px, w, h):
    occ = [sum(1 for x in range(w) if is_fg(px[x, y])) for y in range(h)]
    bands = []
    start = None
    for y, c in enumerate(occ):
        if c > 0 and start is None:
            start = y
        if c == 0 and start is not None:
            bands.append((start, y - 1))
            start = None
    if start is not None:
        bands.append((start, h - 1))

    heights = sorted(b[1] - b[0] + 1 for b in bands)
    median = heights[len(heights) // 2]

    merged = []
    for y0, y1 in bands:
        height = y1 - y0 + 1
        if height > median * MERGE_RATIO:
            lo, hi = y0 + int(height * 0.3), y0 + int(height * 0.7)
            split = min(range(lo, hi + 1), key=lambda y: occ[y])
            merged.append((y0, split - 1))
            merged.append((split, y1))
        else:
            merged.append((y0, y1))
    return merged


def find_frames(px, y0, y1, w):
    cols = [sum(1 for y in range(y0, y1 + 1) if is_fg(px[x, y])) for x in range(w)]
    groups = []
    start = None
    for x, c in enumerate(cols):
        if c > 0 and start is None:
            start = x
        if c == 0 and start is not None:
            groups.append((start, x - 1))
            start = None
    if start is not None:
        groups.append((start, w - 1))

    frames = []
    for x0, x1 in groups:
        ty0 = ty1 = None
        for y in range(y0, y1 + 1):
            if any(is_fg(px[x, y]) for x in range(x0, x1 + 1)):
                if ty0 is None:
                    ty0 = y
                ty1 = y
        frames.append({"x": x0, "y": ty0, "w": x1 - x0 + 1, "h": ty1 - ty0 + 1})

    splits = []
    gaps = [frames[i + 1]["x"] - (frames[i]["x"] + frames[i]["w"]) for i in range(len(frames) - 1)]
    if gaps:
        ordered = sorted(gaps)
        median = ordered[len(ordered) // 2]
        threshold = max(median * GAP_RATIO, median + GAP_MIN_EXTRA)
        for i, gap in enumerate(gaps):
            if gap > threshold:
                splits.append(i + 1)
    return frames, splits


def build_clean(src_img, frames_by_row):
    clean = Image.new("RGBA", src_img.size, (0, 0, 0, 0))
    src = src_img.load()
    dst = clean.load()
    w, h = src_img.size
    keep = set()
    for frames in frames_by_row:
        for f in frames:
            for y in range(f["y"], f["y"] + f["h"]):
                for x in range(f["x"], f["x"] + f["w"]):
                    keep.add((x, y))
    for y in range(h):
        for x in range(w):
            p = src[x, y]
            if (x, y) in keep and is_fg(p):
                dst[x, y] = (p[0], p[1], p[2], 255)
    return clean


def lua_table(rows, image_path):
    lines = []
    lines.append("-- GENERATED by tools/slice_cruz.py -- do not edit by hand.")
    lines.append("-- Source: Castlevania: Dawn of Sorrow - Soma Cruz (asset 19116, by Paddy)")
    lines.append("return {")
    lines.append('\timage = "%s",' % image_path)
    total = sum(len(r["frames"]) for r in rows)
    lines.append("\tframeCount = %d," % total)
    lines.append("\trows = {")
    for r in rows:
        if r["row"] in NON_ANIMATION_ROWS:
            continue
        lines.append("\t\t[%d] = {" % r["row"])
        lines.append("\t\t\ty = %d," % r["y0"])
        parts = []
        for f in r["frames"]:
            parts.append("{x=%d,y=%d,w=%d,h=%d}" % (f["x"], f["y"], f["w"], f["h"]))
        body = ",".join(parts)
        chunk = ""
        indent = "\t\t\tframes = {"
        pad = "\t\t\t\t"
        line = indent
        for i, p in enumerate(parts):
            piece = p + ","
            if len(line) + len(piece) > 110:
                lines.append(line)
                line = pad + piece
            else:
                line += piece
        lines.append(line)
        lines.append("\t\t},")
        lines.append("\t\t\tcount = %d," % len(r["frames"]))
        if r["splits"]:
            lines.append("\t\t\tsplits = {%s}," % ",".join(str(s) for s in r["splits"]))
        lines.append("\t\t},")
    lines.append("\t},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    img = Image.open(SRC).convert("RGBA")
    w, h = img.size
    px = img.load()

    bands = find_row_bands(px, w, h)
    rows = []
    frames_by_row = []
    for i, (y0, y1) in enumerate(bands):
        frames, splits = find_frames(px, y0, y1, w)
        rows.append({"row": i, "y0": y0, "y1": y1, "frames": frames, "splits": splits})
        frames_by_row.append(frames)

    build_clean(img, frames_by_row).save(CLEAN)

    with open(MANIFEST, "w") as fh:
        fh.write(lua_table(rows, "imagens/Cruz/cruz-sprite-sheet-clean.png"))

    total = sum(len(r["frames"]) for r in rows)
    anim_rows = [r for r in rows if r["row"] not in NON_ANIMATION_ROWS]
    print("rows: %d (%d animation rows)" % (len(rows), len(anim_rows)))
    print("frames: %d" % total)
    print("clean: %s" % CLEAN)
    print("manifest: %s" % MANIFEST)

    for r in rows:
        if r["row"] in NON_ANIMATION_ROWS:
            continue
        widths = [f["w"] for f in r["frames"]]
        heights = [f["h"] for f in r["frames"]]
        note = "  groups=%d" % (len(r["splits"]) + 1) if r["splits"] else ""
        print("  row %02d  y=%4d..%4d  frames=%2d  w=%d..%d  h=%d..%d%s"
              % (r["row"], r["y0"], r["y1"], len(r["frames"]),
                 min(widths), max(widths), min(heights), max(heights), note))


if __name__ == "__main__":
    main()
